language: python
python:
- '2.7'
before_install:
- sudo apt-get update -qq
- pip install -r dev-requirements.txt
- pip install -r requirements.txt
script:
- flake8 --select=E121,E123,E126,E226,E24,E704,W503,W504 --ignore=E501 app.py tests
- nosetests
