language: python
python:
- '2.7'
env:
- ES_HOST="search-dos-azul-test-a998691e-uuzze4esxbslgnc4i3pnbzjpq4.us-west-2.es.amazonaws.com"
- TEST_ES_DOMAIN="dos-azul-test-a998691e"
before_install:
- sudo apt-get update -qq
- pip install -r dev-requirements.txt
- pip install -r requirements.txt
before_script:
- python provision/provision.py raze ${TEST_ES_DOMAIN}
- python provision/provision.py populate ${TEST_ES_DOMAIN}
script:
- flake8 --select=E121,E123,E126,E226,E24,E704,W503,W504 --ignore=E501 app.py tests
- nosetests
after_script:
- python provision/provision.py raze ${TEST_ES_DOMAIN}
